"""add active_patient_id to game_players

Revision ID: 4882fd9ea424
Revises: 8545f46a563d
Create Date: 2026-02-13 05:17:43.736913
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4882fd9ea424'
down_revision: Union[str, None] = '8545f46a563d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_players', sa.Column('active_patient_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'game_players', 'patients', ['active_patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_players', type_='foreignkey')
    op.drop_column('game_players', 'active_patient_id')
    # ### end Alembic commands ###
