"""ghost_origin_tracking_and_archive_unlock

Revision ID: 964d770c3a28
Revises: 4882fd9ea424
Create Date: 2026-02-14 17:14:05.858307
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '964d770c3a28'
down_revision: Union[str, None] = '4882fd9ea424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color_fragments', sa.Column('redeemed', sa.Boolean(), nullable=False))
    op.add_column('color_fragments', sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'game_players', 'patients', ['active_patient_id'], ['id'])
    op.add_column('ghosts', sa.Column('current_patient_id', sa.String(length=32), nullable=True))
    op.add_column('ghosts', sa.Column('origin_patient_id', sa.String(length=32), nullable=True))
    op.add_column('ghosts', sa.Column('origin_name', sa.String(length=64), nullable=True))
    op.add_column('ghosts', sa.Column('origin_identity', sa.String(length=128), nullable=True))
    op.add_column('ghosts', sa.Column('origin_soul_color', sa.String(length=1), nullable=True))
    op.add_column('ghosts', sa.Column('origin_ideal_projection', sa.Text(), nullable=True))
    op.add_column('ghosts', sa.Column('origin_archives_json', sa.Text(), nullable=True))
    op.add_column('ghosts', sa.Column('archive_unlock_json', sa.Text(), nullable=False))
    op.add_column('ghosts', sa.Column('origin_name_unlocked', sa.Boolean(), nullable=False))
    op.add_column('ghosts', sa.Column('origin_identity_unlocked', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'ghosts', ['current_patient_id'])
    op.create_unique_constraint(None, 'ghosts', ['origin_patient_id'])
    op.drop_constraint(None, 'ghosts', type_='foreignkey')
    op.create_foreign_key(None, 'ghosts', 'patients', ['origin_patient_id'], ['id'])
    op.create_foreign_key(None, 'ghosts', 'patients', ['current_patient_id'], ['id'])
    op.drop_column('ghosts', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ghosts', sa.Column('patient_id', sa.VARCHAR(length=32), nullable=False))
    op.drop_constraint(None, 'ghosts', type_='foreignkey')
    op.drop_constraint(None, 'ghosts', type_='foreignkey')
    op.create_foreign_key(None, 'ghosts', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'ghosts', type_='unique')
    op.drop_constraint(None, 'ghosts', type_='unique')
    op.drop_column('ghosts', 'origin_identity_unlocked')
    op.drop_column('ghosts', 'origin_name_unlocked')
    op.drop_column('ghosts', 'archive_unlock_json')
    op.drop_column('ghosts', 'origin_archives_json')
    op.drop_column('ghosts', 'origin_ideal_projection')
    op.drop_column('ghosts', 'origin_soul_color')
    op.drop_column('ghosts', 'origin_identity')
    op.drop_column('ghosts', 'origin_name')
    op.drop_column('ghosts', 'origin_patient_id')
    op.drop_column('ghosts', 'current_patient_id')
    op.drop_constraint(None, 'game_players', type_='foreignkey')
    op.drop_column('color_fragments', 'redeemed_at')
    op.drop_column('color_fragments', 'redeemed')
    # ### end Alembic commands ###
