"""initial_schema

Revision ID: d1e9bfd6c0d1
Revises: 
Create Date: 2026-02-14 19:09:37.397879
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1e9bfd6c0d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('preparing', 'active', 'paused', 'ended', name='game_status'), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('flags_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_bindings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_uid', sa.String(length=128), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_binding_platform', 'platform_bindings', ['platform', 'platform_uid'], unique=True)
    op.create_index('ix_binding_user', 'platform_bindings', ['user_id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_region_game', 'regions', ['game_id'], unique=False)
    op.create_index('ix_region_game_code', 'regions', ['game_id', 'code'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_location_region', 'locations', ['region_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=True),
    sa.Column('started_by', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', name='session_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_game', 'sessions', ['game_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('identity', sa.String(length=128), nullable=True),
    sa.Column('portrait_url', sa.String(length=512), nullable=True),
    sa.Column('soul_color', sa.String(length=1), nullable=False),
    sa.Column('personality_archives_json', sa.Text(), nullable=True),
    sa.Column('ideal_projection', sa.Text(), nullable=True),
    sa.Column('current_region_id', sa.String(length=32), nullable=True),
    sa.Column('current_location_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['current_region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patient_game', 'patients', ['game_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_game', 'timeline_events', ['game_id'], unique=False)
    op.create_index('ix_timeline_session_seq', 'timeline_events', ['session_id', 'seq'], unique=False)
    op.create_table('game_players',
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('KP', 'PL', name='player_role'), nullable=False),
    sa.Column('active_patient_id', sa.String(length=32), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    op.create_table('ghosts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('current_patient_id', sa.String(length=32), nullable=True),
    sa.Column('origin_patient_id', sa.String(length=32), nullable=True),
    sa.Column('creator_user_id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('cmyk_json', sa.Text(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('origin_name', sa.String(length=64), nullable=True),
    sa.Column('origin_identity', sa.String(length=128), nullable=True),
    sa.Column('origin_soul_color', sa.String(length=1), nullable=True),
    sa.Column('origin_ideal_projection', sa.Text(), nullable=True),
    sa.Column('origin_archives_json', sa.Text(), nullable=True),
    sa.Column('archive_unlock_json', sa.Text(), nullable=False),
    sa.Column('origin_name_unlocked', sa.Boolean(), nullable=False),
    sa.Column('origin_identity_unlocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['origin_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_patient_id'),
    sa.UniqueConstraint('origin_patient_id')
    )
    op.create_index('ix_ghost_game', 'ghosts', ['game_id'], unique=False)
    op.create_table('color_fragments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('holder_ghost_id', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=1), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('redeemed', sa.Boolean(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['holder_ghost_id'], ['ghosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fragment_game', 'color_fragments', ['game_id'], unique=False)
    op.create_table('print_abilities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ghost_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=1), nullable=False),
    sa.Column('ability_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ghost_id'], ['ghosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_abilities')
    op.drop_index('ix_fragment_game', table_name='color_fragments')
    op.drop_table('color_fragments')
    op.drop_index('ix_ghost_game', table_name='ghosts')
    op.drop_table('ghosts')
    op.drop_table('game_players')
    op.drop_index('ix_timeline_session_seq', table_name='timeline_events')
    op.drop_index('ix_timeline_game', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_patient_game', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_session_game', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_location_region', table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_region_game_code', table_name='regions')
    op.drop_index('ix_region_game', table_name='regions')
    op.drop_table('regions')
    op.drop_index('ix_binding_user', table_name='platform_bindings')
    op.drop_index('ix_binding_platform', table_name='platform_bindings')
    op.drop_table('platform_bindings')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
